all:
	cat \
	"books/Genesis.tsv" \
	"books/Exodus.tsv" \
	"books/Levitikus.tsv" \
	"books/Numeri.tsv" \
	"books/Deuteronomium.tsv" \
	"books/Josua.tsv" \
	"books/Richter.tsv" \
	"books/Rut.tsv" \
	"books/1. Samuel.tsv" \
	"books/2. Samuel.tsv" \
	"books/1. Könige.tsv" \
	"books/2. Könige.tsv" \
	"books/1. Chronik.tsv" \
	"books/2. Chronik.tsv" \
	"books/Esra.tsv" \
	"books/Nehemia.tsv" \
	"books/Ester.tsv" \
	"books/Hiob.tsv" \
	"books/Psalmen.tsv" \
	"books/Sprüche.tsv" \
	"books/Prediger.tsv" \
	"books/Hoheslied.tsv" \
	"books/Jesaja.tsv" \
	"books/Jeremia.tsv" \
	"books/Klagelieder.tsv" \
	"books/Hesekiel.tsv" \
	"books/Daniel.tsv" \
	"books/Hosea.tsv" \
	"books/Joel.tsv" \
	"books/Amos.tsv" \
	"books/Obadja.tsv" \
	"books/Jona.tsv" \
	"books/Micha.tsv" \
	"books/Nahum.tsv" \
	"books/Habakuk.tsv" \
	"books/Zefanja.tsv" \
	"books/Haggai.tsv" \
	"books/Sacharja.tsv" \
	"books/Maleachi.tsv" \
	"books/Tobit.tsv" \
	"books/Judit.tsv" \
	"books/Weisheit.tsv" \
	"books/Sirach.tsv" \
	"books/Baruch.tsv" \
	"books/Brief Jeremias.tsv" \
	"books/1. Makkabäer.tsv" \
	"books/2. Makkabäer.tsv" \
	"books/Zusätze Ester.tsv" \
	"books/Gebet Manasses.tsv" \
	"books/Zusätze Daniel.tsv" \
	"books/Matthäus.tsv" \
	"books/Markus.tsv" \
	"books/Lukas.tsv" \
	"books/Johannes.tsv" \
	"books/Apostelgeschichte.tsv" \
	"books/Römer.tsv" \
	"books/1. Korinther.tsv" \
	"books/2. Korinther.tsv" \
	"books/Galater.tsv" \
	"books/Epheser.tsv" \
	"books/Philipper.tsv" \
	"books/Kolosser.tsv" \
	"books/1. Thessalonicher.tsv" \
	"books/2. Thessalonicher.tsv" \
	"books/1. Timotheus.tsv" \
	"books/2. Timotheus.tsv" \
	"books/Titus.tsv" \
	"books/Philemon.tsv" \
	"books/Hebräer.tsv" \
	"books/Jakobus.tsv" \
	"books/1. Petrus.tsv" \
	"books/2. Petrus.tsv" \
	"books/1. Johannes.tsv" \
	"books/2. Johannes.tsv" \
	"books/3. Johannes.tsv" \
	"books/Judas.tsv" \
	"books/Offenbarung.tsv" \
	> menge.tsv
